print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "C:/Users/Public/DOCUME~1/UNITYP~1/LMCOPR~1/Assets/HALFCY~1.MB"`)
{		
	file -o "C:/Users/Public/DOCUME~1/UNITYP~1/LMCOPR~1/Assets/HALFCY~1.MB";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "C:/Users/Public/DOCUME~1/UNITYP~1/LMCOPR~1/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "C:/Users/Public/DOCUME~1/UNITYP~1/LMCOPR~1/Temp/CommandPipe";

$donepipeKill = `fopen "C:/Users/Public/DOCUME~1/UNITYP~1/LMCOPR~1/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
